services:
  - type: web
    name: course-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn recommender_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0